docker-build:
  # Use the official docker image.
  image: docker:latest
  stage: build
  services:
    - docker:dind
  script:
    - apk add --no-cache docker-compose
    - docker-compose up -d
  only:
    - develop
