# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ops/grpc/infer.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ops/grpc/infer.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14ops/grpc/infer.proto\"\x1f\n\tImgBase64\x12\x12\n\nimg_origin\x18\x01 \x01(\t28\n\x0f\x45xercisePredict\x12%\n\tInference\x12\n.ImgBase64\x1a\n.ImgBase64\"\x00\x62\x06proto3'
)




_IMGBASE64 = _descriptor.Descriptor(
  name='ImgBase64',
  full_name='ImgBase64',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='img_origin', full_name='ImgBase64.img_origin', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=55,
)

DESCRIPTOR.message_types_by_name['ImgBase64'] = _IMGBASE64
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ImgBase64 = _reflection.GeneratedProtocolMessageType('ImgBase64', (_message.Message,), {
  'DESCRIPTOR' : _IMGBASE64,
  '__module__' : 'ops.grpc.infer_pb2'
  # @@protoc_insertion_point(class_scope:ImgBase64)
  })
_sym_db.RegisterMessage(ImgBase64)



_EXERCISEPREDICT = _descriptor.ServiceDescriptor(
  name='ExercisePredict',
  full_name='ExercisePredict',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=57,
  serialized_end=113,
  methods=[
  _descriptor.MethodDescriptor(
    name='Inference',
    full_name='ExercisePredict.Inference',
    index=0,
    containing_service=None,
    input_type=_IMGBASE64,
    output_type=_IMGBASE64,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_EXERCISEPREDICT)

DESCRIPTOR.services_by_name['ExercisePredict'] = _EXERCISEPREDICT

# @@protoc_insertion_point(module_scope)
